// src/Menu.vue
<template>
	<div class="nav">
		<router-link to="/home">Home</router-link> |
		<router-link to="/typers">Typers</router-link>
		<div class="logoff">
			<LogoffButton />
		</div>
	</div>
</template>

<script>
import LogoffButton from '@/login/LogoffButton.vue';

export default {
	components: {
		LogoffButton
	}
};
</script>

<style scoped>
.nav {
	border-bottom: 1px solid #eee;
	padding: 10px;
	background-image: url(./assets/spikes-pattern.png);
	background-repeat: repeat;
}
.logoff {
	display: inline-block;
	margin-left: 12px;
}
</style>

// src/Menu.jsx
import React from 'react';
import {Link} from 'react-router-dom';
import styled from 'styled-components';

function Menu() {
	return (
		<Div0>
			<Link to="/home">Home</Link> | {' '}
			<Link to="/typers">Typers</Link>
		</Div0>
	);
}

const Div0 = styled.div`
	border-bottom: 1px solid #eee;
	padding: 10px;
	background-image: url(/spikes-pattern.png);
	background-repeat: repeat;
`;

export default Menu;
