// src/app/header/Menu.jsx
import React from 'react';
import styled from 'styled-components';

function Menu() {
	return (
		<Div0></Div0>
	);
}

const Div0 = styled.div`
	display: inline-block;
	margin-left: 36px;
	margin-top: 20px;
	width: 1160px;
	height: 35px;
	border: 1px solid #88AEA2;
	border-radius: 7px;
	background-image: linear-gradient(#f7f7f7, #e3e3e3);
`;

export default Menu;

// src/Menu.vue
<template>
	<div class="nav">
		<router-link to="/home">Home</router-link> |
		<router-link to="/inputters">Inputters</router-link>
		<div class="logoff">
			<LogoffButton />
		</div>
	</div>
</template>

<script>
import LogoffButton from '@/login/LogoffButton.vue';

export default {
	components: {
		LogoffButton
	}
};
</script>

<style scoped>
.nav {
	border-bottom: 1px solid #eee;
	padding: 10px;
	background-image: url(./assets/spikes-pattern.png);
	background-repeat: repeat;
}
.logoff {
	display: inline-block;
	margin-left: 12px;
}
</style>
